plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.lombok)
    alias(libs.plugins.spring.boot)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
    archiveClassifier = ''

    from {
        project(':agent:agent').sourceSets.main.output
    }
}

dependencies {
    api project(':agent:agent')

    implementation libs.spring.boot.autoconfigure
}
